/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package jdbcc;

import java.io.File;
import java.io.IOException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.conek;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author rexy
 */
public class DataMahasiswa extends javax.swing.JInternalFrame {

    /**
     * Creates new form DataMahasiswa
     */
    public DataMahasiswa() {
        initComponents();
        datatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnim = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        cmbjur = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        btambah = new javax.swing.JButton();
        bsimpan = new javax.swing.JButton();
        bcari = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        hform = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Mahasiswa");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("NIM");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nama Mahasiswa");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("jrusan");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Alamat");

        txtnim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnimKeyTyped(evt);
            }
        });

        cmbjur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistem Informasi", "Managemen", "Kom.Akuntansi", "Akuntansi" }));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setLabel("Laki - Laki");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setLabel("Wanita");

        btambah.setText("Tambah");
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });

        bsimpan.setText("Simpan");
        bsimpan.setEnabled(false);
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bcari.setText("Cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        bhapus.setText("Hapus");
        bhapus.setEnabled(false);
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bkeluar.setText("KELUAR");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Jurusan", "Jenis Kelamin", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                //        return canEdit [columnIndex];
                return false;
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        table.setShowGrid(true);
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        hform.setText("Hapus Form");
        hform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hformActionPerformed(evt);
            }
        });

        jButton1.setText("cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtnim)
                                .addGap(110, 110, 110))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtnama)
                                .addGap(88, 88, 88))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbjur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(88, 88, 88))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(181, 181, 181))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(193, 193, 193))
                            .addComponent(txtalamat))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(35, 35, 35))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bsimpan)
                        .addGap(18, 18, 18)
                        .addComponent(bcari)
                        .addGap(14, 14, 14)
                        .addComponent(bhapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hform)
                        .addGap(16, 16, 16)
                        .addComponent(bkeluar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbjur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btambah)
                    .addComponent(bsimpan)
                    .addComponent(bcari)
                    .addComponent(bhapus)
                    .addComponent(bkeluar)
                    .addComponent(hform))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        String nim =txtnim.getText();
        String nama =txtnama.getText();
        String jurusan =(String)cmbjur.getSelectedItem();
        String alamat =txtalamat.getText();
        String jeniskelamin = null;

        if(jRadioButton1.isSelected()){
            jeniskelamin = "Laki-Laki";
        }else if(jRadioButton2.isSelected()){
            jeniskelamin = "Wanita";
        }else{
            JOptionPane.showMessageDialog(rootPane, "tidak boleh kosong");
        }
        try{
            Statement statement =(Statement)conek.GetConnection().createStatement();
            statement.executeUpdate("update tabmahasiswa SET nim = '"+nim+"',nama_mhs='"+nama+"',jurusan='"+jurusan+"',jenis_kelamin='"+jeniskelamin+"',alamat='"+alamat+"'WHERE nim = '"+nim+"';");
            clearform();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        datatable();
    }//GEN-LAST:event_bsimpanActionPerformed

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        String nim =txtnim.getText();
        String nama =txtnama.getText();
        String jurusan =(String)cmbjur.getSelectedItem();
        String alamat =txtalamat.getText();
        
        String jeniskelamin = null;
        
        if(jRadioButton1.isSelected()){
            jeniskelamin = "Laki-Laki";
        }else if(jRadioButton2.isSelected()){
            jeniskelamin = "Wanita";
        }else{
            JOptionPane.showMessageDialog(rootPane, "tidak boleh kosong");
        }
        
        try{
            Statement statement =(Statement)conek.GetConnection().createStatement();
            statement.executeUpdate("insert into tabmahasiswa VALUES('"+nim+"','"+nama+"','"+jurusan+"','"+jeniskelamin+"','"+alamat+"');");
            clearform();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        datatable();
    }//GEN-LAST:event_btambahActionPerformed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        try{
            bsimpan.setEnabled(false);
            bhapus.setEnabled(false);
            Statement statement =(Statement)conek.GetConnection().createStatement();
            ResultSet res = statement.executeQuery("select * from tabmahasiswa where nim ='"+txtnim.getText()+"';");
            DefaultTableModel tbl  = new DefaultTableModel();
            tbl.addColumn("NIM");       
            tbl.addColumn("Nama");
            tbl.addColumn("Jurusan");
            tbl.addColumn("Jenis Kelamin");
            tbl.addColumn("Alamat");
            table.setModel(tbl);
            while(res.next()){
                tbl.addRow(new Object[]{
                    res.getString("nim"),         
                    res.getString("nama_mhs"),
                    res.getString("jurusan"),
                    res.getString("jenis_kelamin"),
                    res.getString("alamat")
                });
                table.setModel(tbl);
            }
            
        }catch(Exception e){
             JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_bcariActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
       bsimpan.setEnabled(true);
       bhapus.setEnabled(true);
        int row = table.getSelectedRow();
       DefaultTableModel model = (DefaultTableModel) table.getModel();
       txtnim.setText(model.getValueAt(row,0).toString());
       txtnama.setText(model.getValueAt(row,1).toString());
       cmbjur.getModel().setSelectedItem(model.getValueAt(row,2));
       if(model.getValueAt(row,3).toString().equals("Wanita")){
            jRadioButton2.setSelected(true);   

       }else{
           jRadioButton1.setSelected(true);

       }
       txtalamat.setText(model.getValueAt(row,4).toString());

    }//GEN-LAST:event_tableMouseClicked

    private void txtnimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnimKeyTyped
        char typedChar = evt.getKeyChar();
        String currentText = txtnim.getText();
        if (currentText.isEmpty() && (Character.isWhitespace(typedChar) || Character.isWhitespace(typedChar) || Character.isISOControl(typedChar))||currentText.length() >= 9 || !Character.isLetterOrDigit(typedChar)) {
        evt.consume();
        }  
    }//GEN-LAST:event_txtnimKeyTyped

    private void hformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hformActionPerformed
        clearform();
        datatable();
    }//GEN-LAST:event_hformActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        String nim =txtnim.getText();
        try{
            Statement statement =(Statement)conek.GetConnection().createStatement();
            statement.executeUpdate("delete from tabmahasiswa where nim='"+nim+"';");
            clearform();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        datatable();
        
    }//GEN-LAST:event_bhapusActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        File reportfile = new File(".");
        String dirr ="";
        try{
            Statement statement =(Statement)conek.GetConnection().createStatement();
            ResultSet res = statement.executeQuery("select * from tabmahasiswa;");
            dirr = reportfile.getCanonicalPath()+"/src/iReportdata/";
            JasperDesign design = JRXmlLoader.load(dirr+"report2.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(design);
            
            JRResultSetDataSource rsDataSource = new JRResultSetDataSource(res);
            JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap(),rsDataSource);
            JasperPrintManager.printReport(jp,true);
        }catch(IOException | SQLException | JRException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void datatable(){
        DefaultTableModel tbl  = new DefaultTableModel();
        tbl.addColumn("NIM");       
        tbl.addColumn("Nama");
        tbl.addColumn("Jurusan");
        tbl.addColumn("Jenis Kelamin");
        tbl.addColumn("Alamat");
        table.setModel(tbl);
        try{
            Statement statement =(Statement)conek.GetConnection().createStatement();
            ResultSet res = statement.executeQuery("select * from tabmahasiswa;");
            while(res.next()){
                tbl.addRow(new Object[]{
                    res.getString("nim"),         
                    res.getString("nama_mhs"),
                    res.getString("jurusan"),
                    res.getString("jenis_kelamin"),
                    res.getString("alamat")
                });
                table.setModel(tbl);
            }
        }catch(Exception e){
               JOptionPane.showMessageDialog(rootPane, e);
        } 
    }
    public void clearform(){
        bsimpan.setEnabled(false);
        bhapus.setEnabled(false);
        txtnim.setText("");
        txtnama.setText("");
        cmbjur.getModel().setSelectedItem("Sistem Informasi");
        buttonGroup1.clearSelection();
        txtalamat.setText("");
        txtnim.requestFocus();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton btambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbjur;
    private javax.swing.JButton hform;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnim;
    // End of variables declaration//GEN-END:variables
}
