/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package jdbcc;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JPanel;
import koneksi.conek;
import java.util.ArrayList;
import javax.swing.JTextField;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.net.MalformedURLException;
import java.sql.SQLException;
/**
 *
 * @author rexy
 */
public class transaksi extends javax.swing.JInternalFrame {
    private javax.swing.JPanel[] text1;
    private javax.swing.JLabel[] Jlabel;
    private javax.swing.JLabel Jicon;

    private int count = -1; 
    private int max_row = 10;
    private int empty_count = 0; 
    /**
     * Creates new form transaksi
     */
    public transaksi() {
        initComponents();
        text1_array();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void text1_array(){
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
        try{
            Statement statement =(Statement)conek.GetConnection().createStatement();
            ResultSet res = statement.executeQuery("select * from tabmahasiswa;");
            text1 = new JPanel[10];
            Jlabel = new JLabel[10];
            Jicon = new JLabel();
//            jPanel1.setPreferredSize(new Dimension(300, 400));
            while(res.next()){
                
            count++;
           
//                text1[count].setBackground(new Color(144, 238, 144));
                URL imageUrl = new URL("https://picsum.photos/seed/picsum/50/50");
                Image image = ImageIO.read(imageUrl);
                ImageIcon icon = new ImageIcon(image);
//            text1[count] = new javax.swing.JPanel();  
//            Jlabel[count] = new JLabel("Sds");
//            text1[count].add(Jlabel[count]);
              Jicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\rexy\\Documents\\es.png"));;
            text1[count].add(Jicon);
            jPanel1.setLayout(new GridLayout(0,2,10,10));  
            jPanel1.add( text1[count]); 
           
            }
            
//            jPanel1.revalidate();
//            jPanel1.repaint();
         
            
            
        }catch( IOException | SQLException e){ 
            
           e.printStackTrace();
        }
       
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
